var annotated_dup =
[
    [ "AssetUsageDetectorNamespace", "d2/d96/namespace_asset_usage_detector_namespace.html", [
      [ "AnimationSystemMatch", "d8/df1/class_asset_usage_detector_namespace_1_1_animation_system_match.html", null ],
      [ "AssetImporterDefaultValueMatch", "de/ded/class_asset_usage_detector_namespace_1_1_asset_importer_default_value_match.html", "de/ded/class_asset_usage_detector_namespace_1_1_asset_importer_default_value_match" ],
      [ "AssetUsageDetector", "d3/dcf/class_asset_usage_detector_namespace_1_1_asset_usage_detector.html", "d3/dcf/class_asset_usage_detector_namespace_1_1_asset_usage_detector" ],
      [ "AssetUsageDetectorSettings", "df/ddc/class_asset_usage_detector_namespace_1_1_asset_usage_detector_settings.html", "df/ddc/class_asset_usage_detector_namespace_1_1_asset_usage_detector_settings" ],
      [ "AssetUsageDetectorWindow", "d6/d09/class_asset_usage_detector_namespace_1_1_asset_usage_detector_window.html", "d6/d09/class_asset_usage_detector_namespace_1_1_asset_usage_detector_window" ],
      [ "BehaviourUsageMatch", "dd/d5a/class_asset_usage_detector_namespace_1_1_behaviour_usage_match.html", "dd/d5a/class_asset_usage_detector_namespace_1_1_behaviour_usage_match" ],
      [ "EmptyEnumerator< T >", "d5/d27/class_asset_usage_detector_namespace_1_1_empty_enumerator-1-g.html", "d5/d27/class_asset_usage_detector_namespace_1_1_empty_enumerator-1-g" ],
      [ "GenericSearchMatch", "da/d2f/class_asset_usage_detector_namespace_1_1_generic_search_match.html", "da/d2f/class_asset_usage_detector_namespace_1_1_generic_search_match" ],
      [ "IPropertyAccessor", "dc/d68/interface_asset_usage_detector_namespace_1_1_i_property_accessor.html", "dc/d68/interface_asset_usage_detector_namespace_1_1_i_property_accessor" ],
      [ "ListDrawer< T >", "d3/dca/class_asset_usage_detector_namespace_1_1_list_drawer-1-g.html", "d3/dca/class_asset_usage_detector_namespace_1_1_list_drawer-1-g" ],
      [ "ObjectListDrawer", "d9/daa/class_asset_usage_detector_namespace_1_1_object_list_drawer.html", "d9/daa/class_asset_usage_detector_namespace_1_1_object_list_drawer" ],
      [ "ObjectToSearch", "d6/d75/class_asset_usage_detector_namespace_1_1_object_to_search.html", "d6/d75/class_asset_usage_detector_namespace_1_1_object_to_search" ],
      [ "ObjectToSearchEnumerator", "d2/df5/class_asset_usage_detector_namespace_1_1_object_to_search_enumerator.html", "d2/df5/class_asset_usage_detector_namespace_1_1_object_to_search_enumerator" ],
      [ "ObjectToSearchListDrawer", "da/db8/class_asset_usage_detector_namespace_1_1_object_to_search_list_drawer.html", "da/db8/class_asset_usage_detector_namespace_1_1_object_to_search_list_drawer" ],
      [ "OtherSearchMatch", "d4/da8/class_asset_usage_detector_namespace_1_1_other_search_match.html", null ],
      [ "PrefabMatch", "db/dc7/class_asset_usage_detector_namespace_1_1_prefab_match.html", null ],
      [ "PropertyWrapper< TObject, TValue >", "dd/d96/class_asset_usage_detector_namespace_1_1_property_wrapper-2-g.html", "dd/d96/class_asset_usage_detector_namespace_1_1_property_wrapper-2-g" ],
      [ "ReadOnlySearchMatch", "d5/d7e/class_asset_usage_detector_namespace_1_1_read_only_search_match.html", "d5/d7e/class_asset_usage_detector_namespace_1_1_read_only_search_match" ],
      [ "ReferenceNode", "d9/d78/class_asset_usage_detector_namespace_1_1_reference_node.html", "d9/d78/class_asset_usage_detector_namespace_1_1_reference_node" ],
      [ "ReflectionMatch", "d3/dd9/class_asset_usage_detector_namespace_1_1_reflection_match.html", "d3/dd9/class_asset_usage_detector_namespace_1_1_reflection_match" ],
      [ "SearchMatch", "db/d5f/class_asset_usage_detector_namespace_1_1_search_match.html", "db/d5f/class_asset_usage_detector_namespace_1_1_search_match" ],
      [ "SearchResult", "da/d05/class_asset_usage_detector_namespace_1_1_search_result.html", "da/d05/class_asset_usage_detector_namespace_1_1_search_result" ],
      [ "SearchResultGroup", "d8/d0f/class_asset_usage_detector_namespace_1_1_search_result_group.html", "d8/d0f/class_asset_usage_detector_namespace_1_1_search_result_group" ],
      [ "SearchResultTooltip", "db/d1e/class_asset_usage_detector_namespace_1_1_search_result_tooltip.html", "db/d1e/class_asset_usage_detector_namespace_1_1_search_result_tooltip" ],
      [ "SearchResultTreeView", "d3/d53/class_asset_usage_detector_namespace_1_1_search_result_tree_view.html", "d3/d53/class_asset_usage_detector_namespace_1_1_search_result_tree_view" ],
      [ "SearchResultTreeViewIsolatedView", "dd/dcd/class_asset_usage_detector_namespace_1_1_search_result_tree_view_isolated_view.html", "dd/dcd/class_asset_usage_detector_namespace_1_1_search_result_tree_view_isolated_view" ],
      [ "SearchResultTreeViewState", "d5/d94/class_asset_usage_detector_namespace_1_1_search_result_tree_view_state.html", "d5/d94/class_asset_usage_detector_namespace_1_1_search_result_tree_view_state" ],
      [ "SerializedPropertyMatch", "da/dd7/class_asset_usage_detector_namespace_1_1_serialized_property_match.html", "da/dd7/class_asset_usage_detector_namespace_1_1_serialized_property_match" ],
      [ "Utilities", "d0/d3e/class_asset_usage_detector_namespace_1_1_utilities.html", "d0/d3e/class_asset_usage_detector_namespace_1_1_utilities" ],
      [ "VariableGetterHolder", "d9/da8/struct_asset_usage_detector_namespace_1_1_variable_getter_holder.html", "d9/da8/struct_asset_usage_detector_namespace_1_1_variable_getter_holder" ]
    ] ],
    [ "AYellowpaper", "d7/def/namespace_a_yellowpaper.html", [
      [ "SerializedCollections", "dd/d53/namespace_a_yellowpaper_1_1_serialized_collections.html", [
        [ "Editor", "d7/df2/namespace_a_yellowpaper_1_1_serialized_collections_1_1_editor.html", [
          [ "Data", "d4/ded/namespace_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_data.html", [
            [ "ElementSettings", "d8/de5/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_data_1_1_element_settings.html", "d8/de5/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_data_1_1_element_settings" ]
          ] ],
          [ "Search", "dc/db9/namespace_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search.html", [
            [ "EnumMatcher", "d9/dda/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_enum_matcher.html", "d9/dda/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_enum_matcher" ],
            [ "Matcher", "d2/d25/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_matcher.html", "d2/d25/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_matcher" ],
            [ "Matchers", "d2/d33/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_matchers.html", "d2/d33/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_matchers" ],
            [ "NumericMatcher", "da/dfc/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_numeric_matcher.html", "da/dfc/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_numeric_matcher" ],
            [ "PropertySearchResult", "df/dde/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_property_search_result.html", "df/dde/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_property_search_result" ],
            [ "SearchQuery", "d9/d96/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_search_query.html", "d9/d96/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_search_query" ],
            [ "SearchResultEntry", "dd/d35/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_search_result_entry.html", "dd/d35/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_search_result_entry" ],
            [ "StringMatcher", "d7/da2/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_string_matcher.html", "d7/da2/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_search_1_1_string_matcher" ]
          ] ],
          [ "EditorUserSettings", "d7/dcd/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_editor_user_settings.html", "d7/dcd/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_editor_user_settings" ],
          [ "EditorUserSettingsProvider", "d4/d67/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_editor_user_settings_provider.html", "d4/d67/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_editor_user_settings_provider" ],
          [ "GUIEnabledScope", "d0/d2b/struct_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_g_u_i_enabled_scope.html", "d0/d2b/struct_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_g_u_i_enabled_scope" ],
          [ "LabelWidth", "d5/d2e/struct_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_label_width.html", "d5/d2e/struct_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_label_width" ],
          [ "PagingElement", "d3/d85/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_paging_element.html", "d3/d85/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_paging_element" ],
          [ "RectUtility", "d8/dc7/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_rect_utility.html", "d8/dc7/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_rect_utility" ],
          [ "SerializedDictionaryDrawer", "d5/d74/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_serialized_dictionary_drawer.html", "d5/d74/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_serialized_dictionary_drawer" ],
          [ "SerializedDictionaryInstanceDrawer", "d0/dab/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_serialized_dictionary_instance_drawer.html", "d0/dab/class_a_yellowpaper_1_1_serialized_collections_1_1_editor_1_1_serialized_dictionary_instance_drawer" ]
        ] ],
        [ "KeysGenerators", "d6/d11/namespace_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators.html", [
          [ "EnumGenerator", "df/d43/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_enum_generator.html", "df/d43/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_enum_generator" ],
          [ "IntRangeGenerator", "da/d55/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_int_range_generator.html", "da/d55/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_int_range_generator" ],
          [ "IntSteppingGenerator", "dd/dec/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_int_stepping_generator.html", "dd/dec/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_int_stepping_generator" ],
          [ "KeyListGenerator", "dd/dd7/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator.html", "dd/dd7/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator" ],
          [ "KeyListGeneratorAttribute", "d2/d46/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_attribute.html", "d2/d46/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_attribute" ],
          [ "KeyListGeneratorCache", "d7/da0/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_cache.html", "d7/da0/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_cache" ],
          [ "KeyListGeneratorData", "d6/dcb/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_data.html", "d6/dcb/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_data" ],
          [ "KeyListGeneratorEditor", "d1/dc5/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_editor.html", "d1/dc5/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_editor" ],
          [ "KeyListGeneratorSelectorWindow", "d2/da5/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_selector_window.html", "d2/da5/class_a_yellowpaper_1_1_serialized_collections_1_1_keys_generators_1_1_key_list_generator_selector_window" ]
        ] ],
        [ "SerializedCollectionsUtility", "d7/d7e/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_collections_utility.html", "d7/d7e/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_collections_utility" ],
        [ "SerializedDictionary< TKey, TValue >", "df/dd4/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary-2-g.html", "df/dd4/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary-2-g" ],
        [ "SerializedDictionaryAttribute", "df/d38/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary_attribute.html", "df/d38/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary_attribute" ],
        [ "SerializedDictionarySample", "de/dc3/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary_sample.html", "de/dc3/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary_sample" ],
        [ "SerializedDictionarySampleThree", "dd/d34/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary_sample_three.html", null ],
        [ "SerializedDictionarySampleTwo", "d9/d44/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary_sample_two.html", "d9/d44/class_a_yellowpaper_1_1_serialized_collections_1_1_serialized_dictionary_sample_two" ],
        [ "SerializedKeyValuePair< TKey, TValue >", "d3/dfe/struct_a_yellowpaper_1_1_serialized_collections_1_1_serialized_key_value_pair-2-g.html", "d3/dfe/struct_a_yellowpaper_1_1_serialized_collections_1_1_serialized_key_value_pair-2-g" ]
      ] ]
    ] ],
    [ "BetterHierarchy", "d9/d69/namespace_better_hierarchy.html", [
      [ "Example", "d1/d93/namespace_better_hierarchy_1_1_example.html", [
        [ "UserScriptExample", "de/d76/class_better_hierarchy_1_1_example_1_1_user_script_example.html", null ]
      ] ],
      [ "UnityNamespaceExample", "d4/d46/namespace_better_hierarchy_1_1_unity_namespace_example.html", [
        [ "UnityNamespaceScript", "df/dab/class_better_hierarchy_1_1_unity_namespace_example_1_1_unity_namespace_script.html", null ]
      ] ]
    ] ],
    [ "DG", "d5/d8f/namespace_d_g.html", [
      [ "Tweening", "df/dc0/namespace_d_g_1_1_tweening.html", [
        [ "DOTweenCYInstruction", "d0/d60/class_d_g_1_1_tweening_1_1_d_o_tween_c_y_instruction.html", "d0/d60/class_d_g_1_1_tweening_1_1_d_o_tween_c_y_instruction" ],
        [ "DOTweenModuleAudio", "d3/d86/class_d_g_1_1_tweening_1_1_d_o_tween_module_audio.html", "d3/d86/class_d_g_1_1_tweening_1_1_d_o_tween_module_audio" ],
        [ "DOTweenModulePhysics", "dd/d73/class_d_g_1_1_tweening_1_1_d_o_tween_module_physics.html", "dd/d73/class_d_g_1_1_tweening_1_1_d_o_tween_module_physics" ],
        [ "DOTweenModulePhysics2D", "d1/d0a/class_d_g_1_1_tweening_1_1_d_o_tween_module_physics2_d.html", "d1/d0a/class_d_g_1_1_tweening_1_1_d_o_tween_module_physics2_d" ],
        [ "DOTweenModuleSprite", "d3/df6/class_d_g_1_1_tweening_1_1_d_o_tween_module_sprite.html", "d3/df6/class_d_g_1_1_tweening_1_1_d_o_tween_module_sprite" ],
        [ "DOTweenModuleUI", "d5/d03/class_d_g_1_1_tweening_1_1_d_o_tween_module_u_i.html", "d5/d03/class_d_g_1_1_tweening_1_1_d_o_tween_module_u_i" ],
        [ "DOTweenModuleUnityVersion", "d1/d9e/class_d_g_1_1_tweening_1_1_d_o_tween_module_unity_version.html", "d1/d9e/class_d_g_1_1_tweening_1_1_d_o_tween_module_unity_version" ],
        [ "DOTweenModuleUtils", "d8/d3e/class_d_g_1_1_tweening_1_1_d_o_tween_module_utils.html", "d8/d3e/class_d_g_1_1_tweening_1_1_d_o_tween_module_utils" ]
      ] ]
    ] ],
    [ "FMOD", "d4/db3/namespace_f_m_o_d.html", [
      [ "Studio", "de/db0/namespace_f_m_o_d_1_1_studio.html", [
        [ "ADVANCEDSETTINGS", "de/de5/struct_f_m_o_d_1_1_studio_1_1_a_d_v_a_n_c_e_d_s_e_t_t_i_n_g_s.html", "de/de5/struct_f_m_o_d_1_1_studio_1_1_a_d_v_a_n_c_e_d_s_e_t_t_i_n_g_s" ],
        [ "Bank", "d4/dd3/struct_f_m_o_d_1_1_studio_1_1_bank.html", "d4/dd3/struct_f_m_o_d_1_1_studio_1_1_bank" ],
        [ "BANK_INFO", "dd/d8e/struct_f_m_o_d_1_1_studio_1_1_b_a_n_k___i_n_f_o.html", "dd/d8e/struct_f_m_o_d_1_1_studio_1_1_b_a_n_k___i_n_f_o" ],
        [ "BUFFER_INFO", "d6/db7/struct_f_m_o_d_1_1_studio_1_1_b_u_f_f_e_r___i_n_f_o.html", "d6/db7/struct_f_m_o_d_1_1_studio_1_1_b_u_f_f_e_r___i_n_f_o" ],
        [ "BUFFER_USAGE", "d4/dc0/struct_f_m_o_d_1_1_studio_1_1_b_u_f_f_e_r___u_s_a_g_e.html", "d4/dc0/struct_f_m_o_d_1_1_studio_1_1_b_u_f_f_e_r___u_s_a_g_e" ],
        [ "Bus", "da/dbf/struct_f_m_o_d_1_1_studio_1_1_bus.html", "da/dbf/struct_f_m_o_d_1_1_studio_1_1_bus" ],
        [ "COMMAND_INFO", "d1/d00/struct_f_m_o_d_1_1_studio_1_1_c_o_m_m_a_n_d___i_n_f_o.html", "d1/d00/struct_f_m_o_d_1_1_studio_1_1_c_o_m_m_a_n_d___i_n_f_o" ],
        [ "CommandReplay", "da/db2/struct_f_m_o_d_1_1_studio_1_1_command_replay.html", "da/db2/struct_f_m_o_d_1_1_studio_1_1_command_replay" ],
        [ "CPU_USAGE", "dd/de5/struct_f_m_o_d_1_1_studio_1_1_c_p_u___u_s_a_g_e.html", "dd/de5/struct_f_m_o_d_1_1_studio_1_1_c_p_u___u_s_a_g_e" ],
        [ "EventDescription", "d7/de0/struct_f_m_o_d_1_1_studio_1_1_event_description.html", "d7/de0/struct_f_m_o_d_1_1_studio_1_1_event_description" ],
        [ "EventInstance", "d6/d87/struct_f_m_o_d_1_1_studio_1_1_event_instance.html", "d6/d87/struct_f_m_o_d_1_1_studio_1_1_event_instance" ],
        [ "MEMORY_USAGE", "df/d44/struct_f_m_o_d_1_1_studio_1_1_m_e_m_o_r_y___u_s_a_g_e.html", "df/d44/struct_f_m_o_d_1_1_studio_1_1_m_e_m_o_r_y___u_s_a_g_e" ],
        [ "PARAMETER_DESCRIPTION", "d0/d5f/struct_f_m_o_d_1_1_studio_1_1_p_a_r_a_m_e_t_e_r___d_e_s_c_r_i_p_t_i_o_n.html", "d0/d5f/struct_f_m_o_d_1_1_studio_1_1_p_a_r_a_m_e_t_e_r___d_e_s_c_r_i_p_t_i_o_n" ],
        [ "PARAMETER_ID", "d2/dee/struct_f_m_o_d_1_1_studio_1_1_p_a_r_a_m_e_t_e_r___i_d.html", "d2/dee/struct_f_m_o_d_1_1_studio_1_1_p_a_r_a_m_e_t_e_r___i_d" ],
        [ "PLUGIN_INSTANCE_PROPERTIES", "de/d85/struct_f_m_o_d_1_1_studio_1_1_p_l_u_g_i_n___i_n_s_t_a_n_c_e___p_r_o_p_e_r_t_i_e_s.html", "de/d85/struct_f_m_o_d_1_1_studio_1_1_p_l_u_g_i_n___i_n_s_t_a_n_c_e___p_r_o_p_e_r_t_i_e_s" ],
        [ "PROGRAMMER_SOUND_PROPERTIES", "db/d5f/struct_f_m_o_d_1_1_studio_1_1_p_r_o_g_r_a_m_m_e_r___s_o_u_n_d___p_r_o_p_e_r_t_i_e_s.html", "db/d5f/struct_f_m_o_d_1_1_studio_1_1_p_r_o_g_r_a_m_m_e_r___s_o_u_n_d___p_r_o_p_e_r_t_i_e_s" ],
        [ "SOUND_INFO", "d5/d46/struct_f_m_o_d_1_1_studio_1_1_s_o_u_n_d___i_n_f_o.html", "d5/d46/struct_f_m_o_d_1_1_studio_1_1_s_o_u_n_d___i_n_f_o" ],
        [ "STUDIO_VERSION", "d7/d1b/class_f_m_o_d_1_1_studio_1_1_s_t_u_d_i_o___v_e_r_s_i_o_n.html", "d7/d1b/class_f_m_o_d_1_1_studio_1_1_s_t_u_d_i_o___v_e_r_s_i_o_n" ],
        [ "System", "db/dca/struct_f_m_o_d_1_1_studio_1_1_system.html", "db/dca/struct_f_m_o_d_1_1_studio_1_1_system" ],
        [ "TIMELINE_BEAT_PROPERTIES", "d3/d59/struct_f_m_o_d_1_1_studio_1_1_t_i_m_e_l_i_n_e___b_e_a_t___p_r_o_p_e_r_t_i_e_s.html", "d3/d59/struct_f_m_o_d_1_1_studio_1_1_t_i_m_e_l_i_n_e___b_e_a_t___p_r_o_p_e_r_t_i_e_s" ],
        [ "TIMELINE_MARKER_PROPERTIES", "dc/dbe/struct_f_m_o_d_1_1_studio_1_1_t_i_m_e_l_i_n_e___m_a_r_k_e_r___p_r_o_p_e_r_t_i_e_s.html", "dc/dbe/struct_f_m_o_d_1_1_studio_1_1_t_i_m_e_l_i_n_e___m_a_r_k_e_r___p_r_o_p_e_r_t_i_e_s" ],
        [ "TIMELINE_NESTED_BEAT_PROPERTIES", "da/db0/struct_f_m_o_d_1_1_studio_1_1_t_i_m_e_l_i_n_e___n_e_s_t_e_d___b_e_a_t___p_r_o_p_e_r_t_i_e_s.html", "da/db0/struct_f_m_o_d_1_1_studio_1_1_t_i_m_e_l_i_n_e___n_e_s_t_e_d___b_e_a_t___p_r_o_p_e_r_t_i_e_s" ],
        [ "Union_IntBoolFloatString", "da/dbf/struct_f_m_o_d_1_1_studio_1_1_union___int_bool_float_string.html", "da/dbf/struct_f_m_o_d_1_1_studio_1_1_union___int_bool_float_string" ],
        [ "USER_PROPERTY", "dc/d40/struct_f_m_o_d_1_1_studio_1_1_u_s_e_r___p_r_o_p_e_r_t_y.html", "dc/d40/struct_f_m_o_d_1_1_studio_1_1_u_s_e_r___p_r_o_p_e_r_t_y" ],
        [ "Util", "d7/d40/struct_f_m_o_d_1_1_studio_1_1_util.html", "d7/d40/struct_f_m_o_d_1_1_studio_1_1_util" ],
        [ "VCA", "d4/dbc/struct_f_m_o_d_1_1_studio_1_1_v_c_a.html", "d4/dbc/struct_f_m_o_d_1_1_studio_1_1_v_c_a" ]
      ] ],
      [ "ADVANCEDSETTINGS", "db/d18/struct_f_m_o_d_1_1_a_d_v_a_n_c_e_d_s_e_t_t_i_n_g_s.html", "db/d18/struct_f_m_o_d_1_1_a_d_v_a_n_c_e_d_s_e_t_t_i_n_g_s" ],
      [ "ASYNCREADINFO", "d8/d02/struct_f_m_o_d_1_1_a_s_y_n_c_r_e_a_d_i_n_f_o.html", "d8/d02/struct_f_m_o_d_1_1_a_s_y_n_c_r_e_a_d_i_n_f_o" ],
      [ "ATTRIBUTES_3D", "d4/d97/struct_f_m_o_d_1_1_a_t_t_r_i_b_u_t_e_s__3_d.html", "d4/d97/struct_f_m_o_d_1_1_a_t_t_r_i_b_u_t_e_s__3_d" ],
      [ "Channel", "db/d09/struct_f_m_o_d_1_1_channel.html", "db/d09/struct_f_m_o_d_1_1_channel" ],
      [ "CHANNELCONTROL_DSP_INDEX", "df/dae/struct_f_m_o_d_1_1_c_h_a_n_n_e_l_c_o_n_t_r_o_l___d_s_p___i_n_d_e_x.html", "df/dae/struct_f_m_o_d_1_1_c_h_a_n_n_e_l_c_o_n_t_r_o_l___d_s_p___i_n_d_e_x" ],
      [ "ChannelGroup", "d3/d3e/struct_f_m_o_d_1_1_channel_group.html", "d3/d3e/struct_f_m_o_d_1_1_channel_group" ],
      [ "COMPLEX", "d0/d16/struct_f_m_o_d_1_1_c_o_m_p_l_e_x.html", "d0/d16/struct_f_m_o_d_1_1_c_o_m_p_l_e_x" ],
      [ "CONSTANTS", "d0/db1/class_f_m_o_d_1_1_c_o_n_s_t_a_n_t_s.html", "d0/db1/class_f_m_o_d_1_1_c_o_n_s_t_a_n_t_s" ],
      [ "CPU_USAGE", "d9/dc1/struct_f_m_o_d_1_1_c_p_u___u_s_a_g_e.html", "d9/dc1/struct_f_m_o_d_1_1_c_p_u___u_s_a_g_e" ],
      [ "CREATESOUNDEXINFO", "d8/de8/struct_f_m_o_d_1_1_c_r_e_a_t_e_s_o_u_n_d_e_x_i_n_f_o.html", "d8/de8/struct_f_m_o_d_1_1_c_r_e_a_t_e_s_o_u_n_d_e_x_i_n_f_o" ],
      [ "Debug", "dc/dde/struct_f_m_o_d_1_1_debug.html", "dc/dde/struct_f_m_o_d_1_1_debug" ],
      [ "DSP", "dc/dce/struct_f_m_o_d_1_1_d_s_p.html", "dc/dce/struct_f_m_o_d_1_1_d_s_p" ],
      [ "DSP_BUFFER_ARRAY", "dc/dbc/struct_f_m_o_d_1_1_d_s_p___b_u_f_f_e_r___a_r_r_a_y.html", "dc/dbc/struct_f_m_o_d_1_1_d_s_p___b_u_f_f_e_r___a_r_r_a_y" ],
      [ "DSP_DATA_PARAMETER_INFO", "d7/d65/struct_f_m_o_d_1_1_d_s_p___d_a_t_a___p_a_r_a_m_e_t_e_r___i_n_f_o.html", "d7/d65/struct_f_m_o_d_1_1_d_s_p___d_a_t_a___p_a_r_a_m_e_t_e_r___i_n_f_o" ],
      [ "DSP_DESCRIPTION", "df/d44/struct_f_m_o_d_1_1_d_s_p___d_e_s_c_r_i_p_t_i_o_n.html", "df/d44/struct_f_m_o_d_1_1_d_s_p___d_e_s_c_r_i_p_t_i_o_n" ],
      [ "DSP_LOUDNESS_METER_INFO_TYPE", "de/de9/struct_f_m_o_d_1_1_d_s_p___l_o_u_d_n_e_s_s___m_e_t_e_r___i_n_f_o___t_y_p_e.html", "de/de9/struct_f_m_o_d_1_1_d_s_p___l_o_u_d_n_e_s_s___m_e_t_e_r___i_n_f_o___t_y_p_e" ],
      [ "DSP_LOUDNESS_METER_WEIGHTING_TYPE", "d8/d8d/struct_f_m_o_d_1_1_d_s_p___l_o_u_d_n_e_s_s___m_e_t_e_r___w_e_i_g_h_t_i_n_g___t_y_p_e.html", "d8/d8d/struct_f_m_o_d_1_1_d_s_p___l_o_u_d_n_e_s_s___m_e_t_e_r___w_e_i_g_h_t_i_n_g___t_y_p_e" ],
      [ "DSP_METERING_INFO", "dd/d9e/struct_f_m_o_d_1_1_d_s_p___m_e_t_e_r_i_n_g___i_n_f_o.html", "dd/d9e/struct_f_m_o_d_1_1_d_s_p___m_e_t_e_r_i_n_g___i_n_f_o" ],
      [ "DSP_PARAMETER_3DATTRIBUTES", "dc/d5e/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r__3_d_a_t_t_r_i_b_u_t_e_s.html", "dc/d5e/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r__3_d_a_t_t_r_i_b_u_t_e_s" ],
      [ "DSP_PARAMETER_3DATTRIBUTES_MULTI", "d1/d50/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r__3_d_a_t_t_r_i_b_u_t_e_s___m_u_l_t_i.html", "d1/d50/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r__3_d_a_t_t_r_i_b_u_t_e_s___m_u_l_t_i" ],
      [ "DSP_PARAMETER_ATTENUATION_RANGE", "da/daa/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___a_t_t_e_n_u_a_t_i_o_n___r_a_n_g_e.html", "da/daa/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___a_t_t_e_n_u_a_t_i_o_n___r_a_n_g_e" ],
      [ "DSP_PARAMETER_DESC", "dd/dda/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c.html", "dd/dda/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c" ],
      [ "DSP_PARAMETER_DESC_BOOL", "d5/df9/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___b_o_o_l.html", "d5/df9/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___b_o_o_l" ],
      [ "DSP_PARAMETER_DESC_DATA", "d8/d4c/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___d_a_t_a.html", "d8/d4c/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___d_a_t_a" ],
      [ "DSP_PARAMETER_DESC_FLOAT", "db/da5/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___f_l_o_a_t.html", "db/da5/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___f_l_o_a_t" ],
      [ "DSP_PARAMETER_DESC_INT", "dd/dc3/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___i_n_t.html", "dd/dc3/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___i_n_t" ],
      [ "DSP_PARAMETER_DESC_UNION", "da/d2a/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___u_n_i_o_n.html", "da/d2a/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___u_n_i_o_n" ],
      [ "DSP_PARAMETER_FFT", "df/db2/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_f_t.html", "df/db2/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_f_t" ],
      [ "DSP_PARAMETER_FLOAT_MAPPING", "dc/d2c/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_l_o_a_t___m_a_p_p_i_n_g.html", "dc/d2c/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_l_o_a_t___m_a_p_p_i_n_g" ],
      [ "DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR", "d0/d9a/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_l_o_a_t___m_a_p_p_i_n_g___p_i_e_c_e_w_i_s_e___l_i_n_e_a_r.html", "d0/d9a/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_l_o_a_t___m_a_p_p_i_n_g___p_i_e_c_e_w_i_s_e___l_i_n_e_a_r" ],
      [ "DSP_PARAMETER_OVERALLGAIN", "d5/df7/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___o_v_e_r_a_l_l_g_a_i_n.html", "d5/df7/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___o_v_e_r_a_l_l_g_a_i_n" ],
      [ "DSP_PARAMETER_SIDECHAIN", "d3/d45/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___s_i_d_e_c_h_a_i_n.html", "d3/d45/struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___s_i_d_e_c_h_a_i_n" ],
      [ "DSP_STATE", "dc/daf/struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e.html", "dc/daf/struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e" ],
      [ "DSP_STATE_DFT_FUNCTIONS", "d6/d48/struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___d_f_t___f_u_n_c_t_i_o_n_s.html", "d6/d48/struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___d_f_t___f_u_n_c_t_i_o_n_s" ],
      [ "DSP_STATE_FUNCTIONS", "d1/d33/struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___f_u_n_c_t_i_o_n_s.html", "d1/d33/struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___f_u_n_c_t_i_o_n_s" ],
      [ "DSP_STATE_PAN_FUNCTIONS", "d7/d29/struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___p_a_n___f_u_n_c_t_i_o_n_s.html", "d7/d29/struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___p_a_n___f_u_n_c_t_i_o_n_s" ],
      [ "DSPConnection", "d2/dea/struct_f_m_o_d_1_1_d_s_p_connection.html", "d2/dea/struct_f_m_o_d_1_1_d_s_p_connection" ],
      [ "Error", "dc/dac/class_f_m_o_d_1_1_error.html", "dc/dac/class_f_m_o_d_1_1_error" ],
      [ "ERRORCALLBACK_INFO", "d7/d31/struct_f_m_o_d_1_1_e_r_r_o_r_c_a_l_l_b_a_c_k___i_n_f_o.html", "d7/d31/struct_f_m_o_d_1_1_e_r_r_o_r_c_a_l_l_b_a_c_k___i_n_f_o" ],
      [ "Factory", "de/d6f/struct_f_m_o_d_1_1_factory.html", "de/d6f/struct_f_m_o_d_1_1_factory" ],
      [ "Geometry", "d7/d3c/struct_f_m_o_d_1_1_geometry.html", "d7/d3c/struct_f_m_o_d_1_1_geometry" ],
      [ "GUID", "d6/da2/struct_f_m_o_d_1_1_g_u_i_d.html", "d6/da2/struct_f_m_o_d_1_1_g_u_i_d" ],
      [ "IChannelControl", "d5/da9/interface_f_m_o_d_1_1_i_channel_control.html", "d5/da9/interface_f_m_o_d_1_1_i_channel_control" ],
      [ "Memory", "d2/dc3/struct_f_m_o_d_1_1_memory.html", "d2/dc3/struct_f_m_o_d_1_1_memory" ],
      [ "PLUGINLIST", "dc/d46/struct_f_m_o_d_1_1_p_l_u_g_i_n_l_i_s_t.html", "dc/d46/struct_f_m_o_d_1_1_p_l_u_g_i_n_l_i_s_t" ],
      [ "PORT_INDEX", "d1/dbc/struct_f_m_o_d_1_1_p_o_r_t___i_n_d_e_x.html", "d1/dbc/struct_f_m_o_d_1_1_p_o_r_t___i_n_d_e_x" ],
      [ "PRESET", "da/d4f/class_f_m_o_d_1_1_p_r_e_s_e_t.html", "da/d4f/class_f_m_o_d_1_1_p_r_e_s_e_t" ],
      [ "Reverb3D", "d6/ddd/struct_f_m_o_d_1_1_reverb3_d.html", "d6/ddd/struct_f_m_o_d_1_1_reverb3_d" ],
      [ "REVERB_PROPERTIES", "d4/d89/struct_f_m_o_d_1_1_r_e_v_e_r_b___p_r_o_p_e_r_t_i_e_s.html", "d4/d89/struct_f_m_o_d_1_1_r_e_v_e_r_b___p_r_o_p_e_r_t_i_e_s" ],
      [ "Sound", "dc/dfc/struct_f_m_o_d_1_1_sound.html", "dc/dfc/struct_f_m_o_d_1_1_sound" ],
      [ "SoundGroup", "d4/d8b/struct_f_m_o_d_1_1_sound_group.html", "d4/d8b/struct_f_m_o_d_1_1_sound_group" ],
      [ "StringHelper", "d5/ded/class_f_m_o_d_1_1_string_helper.html", "d5/ded/class_f_m_o_d_1_1_string_helper" ],
      [ "StringWrapper", "da/db2/struct_f_m_o_d_1_1_string_wrapper.html", "da/db2/struct_f_m_o_d_1_1_string_wrapper" ],
      [ "System", "dd/dc4/struct_f_m_o_d_1_1_system.html", "dd/dc4/struct_f_m_o_d_1_1_system" ],
      [ "TAG", "de/db9/struct_f_m_o_d_1_1_t_a_g.html", "de/db9/struct_f_m_o_d_1_1_t_a_g" ],
      [ "Thread", "db/d00/struct_f_m_o_d_1_1_thread.html", "db/d00/struct_f_m_o_d_1_1_thread" ],
      [ "VECTOR", "d1/d1c/struct_f_m_o_d_1_1_v_e_c_t_o_r.html", "d1/d1c/struct_f_m_o_d_1_1_v_e_c_t_o_r" ],
      [ "VERSION", "d7/d4c/class_f_m_o_d_1_1_v_e_r_s_i_o_n.html", "d7/d4c/class_f_m_o_d_1_1_v_e_r_s_i_o_n" ]
    ] ],
    [ "FMODUnity", "d1/da7/namespace_f_m_o_d_unity.html", [
      [ "AutomatableSlots", "d9/db6/struct_f_m_o_d_unity_1_1_automatable_slots.html", "d9/db6/struct_f_m_o_d_unity_1_1_automatable_slots" ],
      [ "BankLoadException", "da/d5e/class_f_m_o_d_unity_1_1_bank_load_exception.html", "da/d5e/class_f_m_o_d_unity_1_1_bank_load_exception" ],
      [ "BankRefAttribute", "d9/d27/class_f_m_o_d_unity_1_1_bank_ref_attribute.html", null ],
      [ "BankRefDrawer", "d0/d37/class_f_m_o_d_unity_1_1_bank_ref_drawer.html", "d0/d37/class_f_m_o_d_unity_1_1_bank_ref_drawer" ],
      [ "BankRefresher", "d2/d46/class_f_m_o_d_unity_1_1_bank_refresher.html", "d2/d46/class_f_m_o_d_unity_1_1_bank_refresher" ],
      [ "BankRefreshWindow", "d6/d1b/class_f_m_o_d_unity_1_1_bank_refresh_window.html", "d6/d1b/class_f_m_o_d_unity_1_1_bank_refresh_window" ],
      [ "BoltIntegration", "d1/dfd/class_f_m_o_d_unity_1_1_bolt_integration.html", "d1/dfd/class_f_m_o_d_unity_1_1_bolt_integration" ],
      [ "BuildStatusWatcher", "d9/d9a/class_f_m_o_d_unity_1_1_build_status_watcher.html", "d9/d9a/class_f_m_o_d_unity_1_1_build_status_watcher" ],
      [ "BusNotFoundException", "dd/d25/class_f_m_o_d_unity_1_1_bus_not_found_exception.html", "dd/d25/class_f_m_o_d_unity_1_1_bus_not_found_exception" ],
      [ "CodecChannelCount", "db/d02/class_f_m_o_d_unity_1_1_codec_channel_count.html", "db/d02/class_f_m_o_d_unity_1_1_codec_channel_count" ],
      [ "CreateEventPopup", "da/daf/class_f_m_o_d_unity_1_1_create_event_popup.html", "da/daf/class_f_m_o_d_unity_1_1_create_event_popup" ],
      [ "EditorBankRef", "da/d1b/class_f_m_o_d_unity_1_1_editor_bank_ref.html", "da/d1b/class_f_m_o_d_unity_1_1_editor_bank_ref" ],
      [ "EditorEventRef", "d5/de2/class_f_m_o_d_unity_1_1_editor_event_ref.html", "d5/de2/class_f_m_o_d_unity_1_1_editor_event_ref" ],
      [ "EditorParamRef", "d0/dfc/class_f_m_o_d_unity_1_1_editor_param_ref.html", "d0/dfc/class_f_m_o_d_unity_1_1_editor_param_ref" ],
      [ "EditorSettings", "d9/d3c/class_f_m_o_d_unity_1_1_editor_settings.html", "d9/d3c/class_f_m_o_d_unity_1_1_editor_settings" ],
      [ "EditorUtils", "dc/d74/class_f_m_o_d_unity_1_1_editor_utils.html", "dc/d74/class_f_m_o_d_unity_1_1_editor_utils" ],
      [ "EmitterRef", "d4/d17/class_f_m_o_d_unity_1_1_emitter_ref.html", "d4/d17/class_f_m_o_d_unity_1_1_emitter_ref" ],
      [ "EventBrowser", "d4/df8/class_f_m_o_d_unity_1_1_event_browser.html", "d4/df8/class_f_m_o_d_unity_1_1_event_browser" ],
      [ "EventCache", "db/d20/class_f_m_o_d_unity_1_1_event_cache.html", "db/d20/class_f_m_o_d_unity_1_1_event_cache" ],
      [ "EventHandler", "d8/da3/class_f_m_o_d_unity_1_1_event_handler.html", "d8/da3/class_f_m_o_d_unity_1_1_event_handler" ],
      [ "EventManager", "d9/dfe/class_f_m_o_d_unity_1_1_event_manager.html", "d9/dfe/class_f_m_o_d_unity_1_1_event_manager" ],
      [ "EventNotFoundException", "dd/d5e/class_f_m_o_d_unity_1_1_event_not_found_exception.html", "dd/d5e/class_f_m_o_d_unity_1_1_event_not_found_exception" ],
      [ "EventRefAttribute", "dd/d9f/class_f_m_o_d_unity_1_1_event_ref_attribute.html", "dd/d9f/class_f_m_o_d_unity_1_1_event_ref_attribute" ],
      [ "EventReference", "d7/d4f/struct_f_m_o_d_unity_1_1_event_reference.html", "d7/d4f/struct_f_m_o_d_unity_1_1_event_reference" ],
      [ "EventReferenceDrawer", "d8/de3/class_f_m_o_d_unity_1_1_event_reference_drawer.html", "d8/de3/class_f_m_o_d_unity_1_1_event_reference_drawer" ],
      [ "EventReferenceUpdater", "d6/d5d/class_f_m_o_d_unity_1_1_event_reference_updater.html", "d6/d5d/class_f_m_o_d_unity_1_1_event_reference_updater" ],
      [ "FileReorganizer", "d5/d7d/class_f_m_o_d_unity_1_1_file_reorganizer.html", "d5/d7d/class_f_m_o_d_unity_1_1_file_reorganizer" ],
      [ "FindAndReplace", "df/dca/class_f_m_o_d_unity_1_1_find_and_replace.html", null ],
      [ "FMODRuntimeManagerOnGUIHelper", "d0/dc1/class_f_m_o_d_unity_1_1_f_m_o_d_runtime_manager_on_g_u_i_helper.html", "d0/dc1/class_f_m_o_d_unity_1_1_f_m_o_d_runtime_manager_on_g_u_i_helper" ],
      [ "HelpContent", "d0/d65/class_f_m_o_d_unity_1_1_help_content.html", "d0/d65/class_f_m_o_d_unity_1_1_help_content" ],
      [ "IEditorSettings", "d7/d6d/interface_f_m_o_d_unity_1_1_i_editor_settings.html", null ],
      [ "LegacyEventRefDrawer", "d6/d15/class_f_m_o_d_unity_1_1_legacy_event_ref_drawer.html", "d6/d15/class_f_m_o_d_unity_1_1_legacy_event_ref_drawer" ],
      [ "ListView", "d5/d78/class_f_m_o_d_unity_1_1_list_view.html", "d5/d78/class_f_m_o_d_unity_1_1_list_view" ],
      [ "NaturalComparer", "db/dc9/class_f_m_o_d_unity_1_1_natural_comparer.html", "db/dc9/class_f_m_o_d_unity_1_1_natural_comparer" ],
      [ "NoIndentScope", "df/dc8/class_f_m_o_d_unity_1_1_no_indent_scope.html", "df/dc8/class_f_m_o_d_unity_1_1_no_indent_scope" ],
      [ "ParamRef", "df/d05/class_f_m_o_d_unity_1_1_param_ref.html", "df/d05/class_f_m_o_d_unity_1_1_param_ref" ],
      [ "ParamRefAttribute", "df/d63/class_f_m_o_d_unity_1_1_param_ref_attribute.html", null ],
      [ "ParamRefDrawer", "d1/d1b/class_f_m_o_d_unity_1_1_param_ref_drawer.html", "d1/d1b/class_f_m_o_d_unity_1_1_param_ref_drawer" ],
      [ "Platform", "d1/d4d/class_f_m_o_d_unity_1_1_platform.html", "d1/d4d/class_f_m_o_d_unity_1_1_platform" ],
      [ "PlatformAndroid", "de/da1/class_f_m_o_d_unity_1_1_platform_android.html", null ],
      [ "PlatformAppleTV", "d1/dfb/class_f_m_o_d_unity_1_1_platform_apple_t_v.html", null ],
      [ "PlatformCallbackHandler", "d5/d19/class_f_m_o_d_unity_1_1_platform_callback_handler.html", "d5/d19/class_f_m_o_d_unity_1_1_platform_callback_handler" ],
      [ "PlatformDefault", "d2/d39/class_f_m_o_d_unity_1_1_platform_default.html", "d2/d39/class_f_m_o_d_unity_1_1_platform_default" ],
      [ "PlatformGroup", "d3/ddd/class_f_m_o_d_unity_1_1_platform_group.html", null ],
      [ "PlatformIOS", "df/d2f/class_f_m_o_d_unity_1_1_platform_i_o_s.html", "df/d2f/class_f_m_o_d_unity_1_1_platform_i_o_s" ],
      [ "PlatformLinux", "d2/d6b/class_f_m_o_d_unity_1_1_platform_linux.html", null ],
      [ "PlatformMac", "d9/d49/class_f_m_o_d_unity_1_1_platform_mac.html", null ],
      [ "PlatformMobileHigh", "d0/df0/class_f_m_o_d_unity_1_1_platform_mobile_high.html", null ],
      [ "PlatformMobileLow", "db/d6e/class_f_m_o_d_unity_1_1_platform_mobile_low.html", null ],
      [ "PlatformPlayInEditor", "d4/d90/class_f_m_o_d_unity_1_1_platform_play_in_editor.html", "d4/d90/class_f_m_o_d_unity_1_1_platform_play_in_editor" ],
      [ "PlatformVisionOS", "d4/df4/class_f_m_o_d_unity_1_1_platform_vision_o_s.html", null ],
      [ "PlatformWebGL", "dd/d41/class_f_m_o_d_unity_1_1_platform_web_g_l.html", null ],
      [ "PlatformWindows", "d9/def/class_f_m_o_d_unity_1_1_platform_windows.html", null ],
      [ "RuntimeManager", "d7/d1b/class_f_m_o_d_unity_1_1_runtime_manager.html", "d7/d1b/class_f_m_o_d_unity_1_1_runtime_manager" ],
      [ "RuntimeUtils", "d0/d63/class_f_m_o_d_unity_1_1_runtime_utils.html", "d0/d63/class_f_m_o_d_unity_1_1_runtime_utils" ],
      [ "SerializedPropertyExtensions", "d4/de0/class_f_m_o_d_unity_1_1_serialized_property_extensions.html", "d4/de0/class_f_m_o_d_unity_1_1_serialized_property_extensions" ],
      [ "Settings", "dc/de0/class_f_m_o_d_unity_1_1_settings.html", "dc/de0/class_f_m_o_d_unity_1_1_settings" ],
      [ "SettingsEditor", "d2/d72/class_f_m_o_d_unity_1_1_settings_editor.html", "d2/d72/class_f_m_o_d_unity_1_1_settings_editor" ],
      [ "SetupWizardWindow", "d3/d61/class_f_m_o_d_unity_1_1_setup_wizard_window.html", "d3/d61/class_f_m_o_d_unity_1_1_setup_wizard_window" ],
      [ "SimpleHelp", "d1/d7f/class_f_m_o_d_unity_1_1_simple_help.html", "d1/d7f/class_f_m_o_d_unity_1_1_simple_help" ],
      [ "SimpleTreeView", "da/d79/class_f_m_o_d_unity_1_1_simple_tree_view.html", "da/d79/class_f_m_o_d_unity_1_1_simple_tree_view" ],
      [ "StagingSystem", "d9/d36/class_f_m_o_d_unity_1_1_staging_system.html", "d9/d36/class_f_m_o_d_unity_1_1_staging_system" ],
      [ "StudioBankLoader", "d0/da3/class_f_m_o_d_unity_1_1_studio_bank_loader.html", "d0/da3/class_f_m_o_d_unity_1_1_studio_bank_loader" ],
      [ "StudioBankLoaderEditor", "db/df0/class_f_m_o_d_unity_1_1_studio_bank_loader_editor.html", "db/df0/class_f_m_o_d_unity_1_1_studio_bank_loader_editor" ],
      [ "StudioEventEmitter", "d0/de5/class_f_m_o_d_unity_1_1_studio_event_emitter.html", "d0/de5/class_f_m_o_d_unity_1_1_studio_event_emitter" ],
      [ "StudioEventEmitterEditor", "d7/d41/class_f_m_o_d_unity_1_1_studio_event_emitter_editor.html", "d7/d41/class_f_m_o_d_unity_1_1_studio_event_emitter_editor" ],
      [ "StudioEventEmitterGizoDrawer", "d1/d0c/class_f_m_o_d_unity_1_1_studio_event_emitter_gizo_drawer.html", null ],
      [ "StudioGlobalParameterTrigger", "df/ddc/class_f_m_o_d_unity_1_1_studio_global_parameter_trigger.html", "df/ddc/class_f_m_o_d_unity_1_1_studio_global_parameter_trigger" ],
      [ "StudioGlobalParameterTriggerEditor", "dd/d5b/class_f_m_o_d_unity_1_1_studio_global_parameter_trigger_editor.html", "dd/d5b/class_f_m_o_d_unity_1_1_studio_global_parameter_trigger_editor" ],
      [ "StudioListener", "d5/db8/class_f_m_o_d_unity_1_1_studio_listener.html", "d5/db8/class_f_m_o_d_unity_1_1_studio_listener" ],
      [ "StudioListenerEditor", "da/d2f/class_f_m_o_d_unity_1_1_studio_listener_editor.html", "da/d2f/class_f_m_o_d_unity_1_1_studio_listener_editor" ],
      [ "StudioParameterTrigger", "dd/da3/class_f_m_o_d_unity_1_1_studio_parameter_trigger.html", "dd/da3/class_f_m_o_d_unity_1_1_studio_parameter_trigger" ],
      [ "StudioParameterTriggerEditor", "d4/d73/class_f_m_o_d_unity_1_1_studio_parameter_trigger_editor.html", "d4/d73/class_f_m_o_d_unity_1_1_studio_parameter_trigger_editor" ],
      [ "SystemNotInitializedException", "d3/d99/class_f_m_o_d_unity_1_1_system_not_initialized_exception.html", "d3/d99/class_f_m_o_d_unity_1_1_system_not_initialized_exception" ],
      [ "ThreadAffinityGroup", "d2/df7/class_f_m_o_d_unity_1_1_thread_affinity_group.html", "d2/df7/class_f_m_o_d_unity_1_1_thread_affinity_group" ],
      [ "VCANotFoundException", "d0/db4/class_f_m_o_d_unity_1_1_v_c_a_not_found_exception.html", "d0/db4/class_f_m_o_d_unity_1_1_v_c_a_not_found_exception" ]
    ] ],
    [ "FMODUnityResonance", "d9/dc6/namespace_f_m_o_d_unity_resonance.html", [
      [ "FmodResonanceAudio", "d5/d97/class_f_m_o_d_unity_resonance_1_1_fmod_resonance_audio.html", "d5/d97/class_f_m_o_d_unity_resonance_1_1_fmod_resonance_audio" ],
      [ "FmodResonanceAudioRoom", "db/d8b/class_f_m_o_d_unity_resonance_1_1_fmod_resonance_audio_room.html", "db/d8b/class_f_m_o_d_unity_resonance_1_1_fmod_resonance_audio_room" ],
      [ "FmodResonanceAudioRoomEditor", "d4/ded/class_f_m_o_d_unity_resonance_1_1_fmod_resonance_audio_room_editor.html", null ]
    ] ],
    [ "ProjectNull", "d2/d7d/namespace_project_null.html", [
      [ "DocTools", "d3/d73/namespace_project_null_1_1_doc_tools.html", [
        [ "DoxyFile", "d5/dff/class_project_null_1_1_doc_tools_1_1_doxy_file.html", "d5/dff/class_project_null_1_1_doc_tools_1_1_doxy_file" ],
        [ "DoxySettings", "d2/da2/struct_project_null_1_1_doc_tools_1_1_doxy_settings.html", "d2/da2/struct_project_null_1_1_doc_tools_1_1_doxy_settings" ],
        [ "DoxyWindow", "dd/de5/class_project_null_1_1_doc_tools_1_1_doxy_window.html", null ],
        [ "ProcessRunner", "de/d43/class_project_null_1_1_doc_tools_1_1_process_runner.html", "de/d43/class_project_null_1_1_doc_tools_1_1_process_runner" ]
      ] ]
    ] ],
    [ "Utilities", "de/dc7/namespace_utilities.html", [
      [ "BetterHierarchy", "df/da9/namespace_utilities_1_1_better_hierarchy.html", [
        [ "BetterHierarchyIconDisplayer", "de/dba/class_utilities_1_1_better_hierarchy_1_1_better_hierarchy_icon_displayer.html", null ],
        [ "BetterHierarchyPreferences", "dd/ddf/class_utilities_1_1_better_hierarchy_1_1_better_hierarchy_preferences.html", "dd/ddf/class_utilities_1_1_better_hierarchy_1_1_better_hierarchy_preferences" ],
        [ "HierarchyObjectStatus", "dc/dbd/struct_utilities_1_1_better_hierarchy_1_1_hierarchy_object_status.html", "dc/dbd/struct_utilities_1_1_better_hierarchy_1_1_hierarchy_object_status" ],
        [ "MouseStatus", "d4/d8c/class_utilities_1_1_better_hierarchy_1_1_mouse_status.html", "d4/d8c/class_utilities_1_1_better_hierarchy_1_1_mouse_status" ],
        [ "Preference< T >", "d9/dca/class_utilities_1_1_better_hierarchy_1_1_preference-1-g.html", "d9/dca/class_utilities_1_1_better_hierarchy_1_1_preference-1-g" ],
        [ "UnityEditorBackgroundColor", "da/df5/class_utilities_1_1_better_hierarchy_1_1_unity_editor_background_color.html", "da/df5/class_utilities_1_1_better_hierarchy_1_1_unity_editor_background_color" ]
      ] ]
    ] ],
    [ "AudioEmitterSettings", "d0/d51/class_audio_emitter_settings.html", "d0/d51/class_audio_emitter_settings" ],
    [ "AudioEmitterTools", "d8/d49/class_audio_emitter_tools.html", "d8/d49/class_audio_emitter_tools" ],
    [ "CreateScriptTemplates", "d8/dcc/class_create_script_templates.html", "d8/dcc/class_create_script_templates" ],
    [ "FrameInput", "da/db8/struct_frame_input.html", "da/db8/struct_frame_input" ],
    [ "GrabbableObject", "de/df2/class_grabbable_object.html", null ],
    [ "GravityGunController", "d6/dba/class_gravity_gun_controller.html", null ],
    [ "influenceableObject", "d7/dce/classinfluenceable_object.html", null ],
    [ "InputManager", "df/dd1/class_input_manager.html", "df/dd1/class_input_manager" ],
    [ "InspectorReadOnly", "d8/d23/class_inspector_read_only.html", null ],
    [ "InspectorReadOnlyDrawer", "d5/d5f/class_inspector_read_only_drawer.html", "d5/d5f/class_inspector_read_only_drawer" ],
    [ "Interactable", "dc/dc0/class_interactable.html", "dc/dc0/class_interactable" ],
    [ "InteractionManager2D", "d9/d70/class_interaction_manager2_d.html", null ],
    [ "Lever", "d6/d65/class_lever.html", null ],
    [ "MultiAudioEmitter", "d9/d11/class_multi_audio_emitter.html", "d9/d11/class_multi_audio_emitter" ],
    [ "Outline2D", "d5/df2/class_outline2_d.html", "d5/df2/class_outline2_d" ],
    [ "PersistentObjectsManager", "d5/d84/class_persistent_objects_manager.html", "d5/d84/class_persistent_objects_manager" ],
    [ "PhysicsObject", "d6/db5/class_physics_object.html", "d6/db5/class_physics_object" ],
    [ "PlayerAnimator", "d4/da1/class_player_animator.html", null ],
    [ "PlayerControls", "db/d7d/class_player_controls.html", "db/d7d/class_player_controls" ],
    [ "PlayerMovementController", "d2/dcb/class_player_movement_controller.html", "d2/dcb/class_player_movement_controller" ],
    [ "ScriptableStats", "da/dd5/class_scriptable_stats.html", "da/dd5/class_scriptable_stats" ],
    [ "SimpleAudioEmitter", "d1/da0/class_simple_audio_emitter.html", "d1/da0/class_simple_audio_emitter" ],
    [ "SoundManager", "d5/dd9/class_sound_manager.html", "d5/dd9/class_sound_manager" ]
];