using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.Serialization;

/* -----------------------------------------------------------
 * Author:
 * Ian Fletcher
 * 
 * Modified By:
 * 
 */// --------------------------------------------------------

// Some comments have been generated by GPT

/// <summary>
/// 2‑D pressure‑plate controller.
/// Attach this to the DYNAMIC plate Rigidbody2D that is linked by
/// a SpringJoint2D to a KINEMATIC base.  The plate fires events when
/// it sinks (compresses the spring) beyond a configurable threshold.
/// </summary>
public class PressurePlate2D : MonoBehaviour
{
    [Header("Activation options")]
    [SerializeField, Tooltip(
        "Optional.  If > 0, the script converts this 'required mass' into\n" +
        "a compression distance using Hooke's law based on the joint's\n" +
        "frequency.  Leave at 0 if you want to set Compress Distance directly.")]
    private float requiredMassKg = 0f;

    [SerializeField, Tooltip("Plate activates once it sinks by at least this many meters.")]
    private float _compressDistance = 0.05f;
    
    
    [SerializeField, Range(0, 100), Tooltip("Reduce the computed frequency by this % (0‑100).\n" +
             "  0 % = exact math value\n" +
             " 10 % = frequency * 0.90  (softer)\n" +
             " 25 % = frequency * 0.75  (much softer)")]
    private float frequencyOffsetPercent = 0f;

    [SerializeField] private ActivationMode _activationMode;
    private enum ActivationMode //What is allowed to activate the switch.
    {
        PlayerAndObjects,
        PlayerOnly,
        ObjectsOnly
    }
    
    [Header("References")]
    [SerializeField] private Rigidbody2D _plateRB; // dynamic plate body
    [SerializeField] private Collider2D _plateCol;
    [SerializeField] private SpringJoint2D _sj; // spring linking plate to base
    [SerializeField] private TextMeshProUGUI _massTargetText;
    [SerializeField] private GameObject statusBarActive;
    [SerializeField] private GameObject statusBarInactive;

    [Header("Events")]
    public UnityEvent onPressed;   // invoked once when plate first crosses threshold
    public UnityEvent onReleased;  // invoked once when it rises back up
    
    [Header("Readouts")]
    [SerializeField, InspectorReadOnly] private float _restY;       // plate Y‑pos at rest (uncompressed)
    [SerializeField, InspectorReadOnly] private bool _isPressed;   // current state latch

    #region Unity Callbacks

    private void Awake()
    {
        _massTargetText.text = requiredMassKg.ToString("0.0");
        _restY = _plateRB.transform.localPosition.y;
        AutoConfigureFrequency();

        //The numbers of layers are hardcoded because they will not change.
        if (_activationMode == ActivationMode.ObjectsOnly) _plateCol.excludeLayers += 6;
        else if (_activationMode == ActivationMode.PlayerOnly)
        {
            for (int i = 0; i < 32; i++)
            {
                if (i == 6 || i == 10) continue; //Skips layers that need to be touched.

                string name = LayerMask.LayerToName(i);

                if (string.IsNullOrEmpty(name)) continue; //Ensures only used layers count.

                _plateCol.excludeLayers += 1 << i;
            }
        }
    }
    
    private void AutoConfigureFrequency()
    {
        // Hooke: m*g = k*x      and   k = (2πf)² * mPlate
        float g = Mathf.Abs(Physics2D.gravity.y);
        float k = (requiredMassKg * g) / _compressDistance;

        // Effective mass can't be zero
        float effectiveMass = Mathf.Max(_plateRB.mass, 0.001f);

        float f = Mathf.Sqrt(k / effectiveMass) / (2f * Mathf.PI);

        // Apply percent offset (softer spring)
        float factor = 1f - frequencyOffsetPercent / 100f;
        f = Mathf.Max(0.01f, f * factor);               // clamp to positive

        _sj.autoConfigureDistance = false;               // keep custom distance
        _sj.frequency             = f;
    }
    
    private void FixedUpdate()
    {
        // If the plate has escaped the boundaries, reset it
        if (_plateRB.transform.localPosition.y > _restY)
        {
            _plateRB.transform.localPosition = new Vector2(_plateRB.transform.localPosition.x,_restY);
        }
        
        /*  How far has the plate sunk?  Positive when below the rest height. */
        float currentCompression = _restY - _plateRB.transform.localPosition.y;

        /* ---------- Rising edge: plate just got pressed ---------- */
        if (!_isPressed && currentCompression >= _compressDistance)
        {
            _isPressed = true;
            onPressed?.Invoke();

            statusBarActive.SetActive(true);
            statusBarInactive.SetActive(false);
        }

        /* ---------- Falling edge: plate just got released ----------
           A little hysteresis (half the threshold) prevents rapid
           flip‑flopping when an object is just at the margin.        */
        else if (_isPressed && currentCompression < _compressDistance * 0.5f)
        {
            _isPressed = false;
            onReleased?.Invoke();

            statusBarActive.SetActive(false);
            statusBarInactive.SetActive(true);
        }
    }
    #endregion



#if UNITY_EDITOR

    // Gizmo to visualise the activation depth when object is selected.
    private void OnDrawGizmosSelected()
    {
        Vector3 top    = new Vector3(transform.localPosition.x, _plateRB.transform.localPosition.y, 0f);
        Vector3 bottom = top + Vector3.down * _compressDistance;

        Gizmos.color = Color.yellow;
        Gizmos.DrawLine(top, bottom);          // vertical marker
        Gizmos.DrawSphere(bottom, 0.03f);      // little dot at threshold
    }
#endif
}
